using System.Collections;
using System.Collections.Generic;
using UnityEngine;
 
public enum BackGroundClipName{
    MUSIC_1, MUSIC_2, MUSIC_3, LAST_NO_USE
}

public enum SCENE { MAIN_MENU, PAUSE_MENU, LEVEL, LAST_NO_USE}

public enum PLAYER_ANIMATION { IDLEBOTTOM, IDLETOP, IDLERIGTH, IDLELEFT ,MOVE_LEFT, MOVE_RIGHT, MOVE_TOP, MOVE_BOTTOM, EXECUTE_LEFT, EXECUTE_RIGHT, OBSERVATION_LEFT, OBSERVATION_RIGHT, LAST_NO_USE}
