using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum AudioClipName
{
    ENEMY_HIT, ENEMY_KILL, PLAYER_MACHINE_1, PLAYER_MACHINE_2, PLAYER_MACHINE_3, PLAYER_MACHINE_4, PLAYER_WALK, PLAYER_GROUNDPOUND, PLAYER_DASH, PLAYER_JUMP, MINE_COAL,
    RECOLECT_WATTER, SHOOTSOUND, PLAYER_WALLJUMP, CLICK_MENU, SOUND_LAVA, LAST_NO_USE
}
 
public enum BackGroundClipName{
    MUSIC_1, MUSIC_2, MUSIC_3, LAST_NO_USE
}

public enum SCENE { MAIN_MENU, PAUSE_MENU, LEVEL, LAST_NO_USE}

public enum PLAYER_ANIMATION { IDLE, MOVE_LEFT, MOVE_RIGHT, MOVE_TOP, MOVE_BOTTOM, LAST_NO_USE}
